name: Backend Dev Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_validate_backend:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repo
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up JDK 22 for backend build
      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: '22'

      # Run Static Code Analysis with SonarQube
      - name: Run Static Code Analysis
        run: |
          mvn sonar:sonar

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          mvn test

      # Run Code Coverage with Jacoco
      - name: Generate Code Coverage Report
        run: |
          mvn jacoco:report

      # Validate the results and give feedback
      - name: Validate and Provide Feedback
        run: |
          echo "Validation feedback..."
