name: Backend NIT Pipeline

on:
  workflow_run:
    workflows: ["Backend SIT Pipeline"]
    types:
      - completed

jobs:
  deploy_and_test_nit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Deploy to NIT environment
      - name: Deploy to NIT
        run: |
          kubectl apply -f eks/backend/backend-deployment.yaml
          kubectl apply -f eks/backend/backend-service.yaml

      # Run JMeter tests
      - name: Run JMeter Tests
        run: |
          jmeter -n -t load-tests.jmx -l results.jtl
