name: Setup Terraform State Backend Workflow-01

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.6

      - name: Set AWS Credentials
        run: |
          echo "Setting AWS environment variables"
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=eu-west-2
        shell: bash

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform/terraform-state-backend

      - name: Apply Terraform (Create S3 Bucket and DynamoDB)
        run: terraform apply -auto-approve
        working-directory: terraform/terraform-state-backend
