name: Setup Terraform State Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to the appropriate branch

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.x  # Specify your version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Change to your AWS region

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform/terraform-state-backend

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform/terraform-state-backend
